name: Run Unit Tests

# Această secțiune dictează CÂND se rulează acțiunea
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: fedora-latest # Mașina virtuală standard de pe GitHub
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Descarcă codul tău pe mașina virtuală
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      # Instalează pytest pe mașina virtuală
      run: pip install pytest

    - name: Run tests
      # Rulează pytest în folderul corect
      run: pytest laboratories/cicd-documentation
